### ISSUE TITLE
SASS?

### ISSUE THREAD

**Issue by surfjedi** [aki77/atom-source-preview#9]
Any chance for SASS support?

**Comment by aki77** [comment]
I have no plan at the moment.
Welcome new provider.
Please refer to the [atom-source-preview-babel](https://github.com/aki77/atom-source-preview-babel).

**Comment by danielbayley** [comment]
+1.

**Comment by danielbayley** [comment]
I just released [source-preview-sass](https://atom.io/packages/source-preview-sass). Although I can't quite seem to get the source mapping to work… @aki77 Any [ideas](https://github.com/danielbayley/atom-source-preview-sass/blob/master/lib/scss-provider.coffee#L33)?

**Comment by danielbayley** [comment]
Never mind… I just released patch `0.1.1` which fixes source maps. This can be closed now @surfjedi 👍

**Comment by surfjedi** [comment]
Cool thanks - but whats to short cut? using source-preview from the palette doesn't do any thing on a .scss file?

**Comment by danielbayley** [comment]
> but whats to short cut?

Not quite sure what you're asking there… I'm sure you've done `apm install source-preview-sass`?

I suspect you might be getting a 'Missing binding' error as I suddenly am after updating my homebrew installed version of Node to 6, which is causing a problem with node-sass (the only dependency of my package). It [seems this will be fixed in their next release](https://github.com/sass/node-sass/issues/1504), but in the meantime (if I'm right, and you're on a mac) then you can download the correct [darwin-x64-47](https://github.com/sass/node-sass/releases/download/v3.7.0/darwin-x64-47_binding.node) binding, rename the downloaded file from `darwin-x64-47_binding.node` to `binding.node` and place it inside a `darwin-x64-47` folder. Then move this folder to `$ATOM_HOME/packages/source-preview-sass/node_modules/node-sass/vendor/darwin-x64-47/binding.node` which fixes the problem until the upstream is fixed, at which point I'll update the dependency and the Atom package.

Hope that helps. If there is still an issue then just open one [on my package](https://github.com/danielbayley/atom-source-preview-sass/issues) as this issue should be closed.

**Comment by danielbayley** [comment]
@surfjedi It turned out that _node-sass_ is currently not compatible with Electron (Atom), so the update didn't fix the problem. It might be in future… at which point I'll probably switch dependencies back to node-sass, but for now I implemented [a workaround](https://github.com/danielbayley/atom-source-preview-sass/commit/e90c801139a57a0839f54f6c68b3950a032c2d50). So package should work smoothly now, although it takes a while to install.

@aki77 This can be closed.

**Comment by aki77** [comment]
@danielbayley Thanks!
